### PR TITLE
Move chats to a separate slideout menu on the right side

### PR DESCRIPTION
**Pull request by pitaj**
- Switched to the Pulling library
- Moved nav menu to the left side, as is normal elsewhere
- Added chat button on right side
- Unread icon on it shows unread chats
- Added slideout menu on right for only chats
- Both sides will slide open and everything
- Switched to drawer menus instead of the previous reveal style menus

### Screenshots

screen shot 2017-11-10 at 19 39 05
screen shot 2017-11-10 at 19 39 19
screen shot 2017-11-10 at 19 39 15
screen shot 2017-11-10 at 19 39 26
screen shot 2017-11-10 at 19 37 08

### CODE REVIEW

**Comment by barisusakli** [comment]
Can we have the icons match in size the chat icon box is smaller than the other one, makes my OCD go 🔩

**Comment by pitaj** [comment]
Pretty sure they're the same height. Are you asking for equal width as well?

**Comment by barisusakli** [comment]
Oops sorry yeah I meant width of the boxes

**Comment by pitaj** [comment]
I think it looks a lot worse, to be honest. The chat button just looks fat now.

image

Maybe this looks better? Uses the fontawesome version of the hamburger icon instead:

screen shot 2017-11-17 at 21 14 20

**Comment by barisusakli** [comment]
yeah both smaller is good

**Comment by pitaj** [comment]
Ok I think this is about final. I removed the button borders and made them full-height, so now they're easier to tap and larger icons.

screen shot 2017-11-18 at 17 10 43

**Pull request merged**
