### PR TITLE
display complete topic title in category page on mobile

### PR DESCRIPTION
**Pull request by pichalite**
## Changes this to.....

screen shot 2015-05-15 at 12 24 56 pm

## this...

screen shot 2015-05-15 at 12 33 27 pm

### CODE REVIEW

**Comment by pichalite** [comment]
hopefully I am not breaking anything

**Comment by psychobunny** [comment]
The reason why I didn't do this is because I felt the right border looks weird because it's always the same height.

I didn't try stretching the border to match. That might look good.. what do you think?

**Comment by pichalite** [comment]
How about removing the border on mobile devices as the recent post is hidden?

**Comment by julianlam** [comment]
Yeah I think it looks good.

**Comment by psychobunny** [comment]
> How about removing the border on mobile devices as the recent post is hidden?

Well I was planning to implement a slide mechanic on mobile, so you can slide left for options (giving away my secret plans :p)

**Comment by pichalite** [comment]
Oooh fancy. Nice, I like slide options. :+1: 

Any chance you can make that like a theme add-on or something so that other theme devs can add it to their themes (thinking about material theme :trollface: )?

I would get rid of the border anyway.

**Comment by psychobunny** [comment]
> Any chance you can make that like a theme add-on or something 

Probably. I'm already planning on taking out the loading progress bar out of persona and lav and making it a dependent plugin, so this should be a plugin as well. Now that we have components its more easier to pull off across multiple themes

I think lets hold off on this PR for a bit, let me figure out a better look for the view. I definitely agree that the entire title should be shown on mobile though :+1:

**Comment by pichalite** [comment]
sounds good :+1:

**Comment by barisusakli** [comment]
image

**Pull request closed without merging**
