### PR TITLE
Fixed navbar autohide after viewport resize

### PR DESCRIPTION
**Pull request by petergood**
https://github.com/NodeBB/NodeBB/issues/6170

### CODE REVIEW

**Comment by pitaj** [comment]
I'm pretty sure there's a CSS fix for this. Would go something like:
- Always enable the autohiding
- Use CSS to disable to autohiding when applicable

**Comment by pitaj** [comment]
I'm also very hesitant to add `resize` handlers, especially running `getBootstrapEnvironment` on every resize. `getBootstrapEnvironment` is a very slow operation, running it on every resize results in very slow operations.

**Comment by petergood** [comment]
That's a good point, I have done as you suggested in my latest commit. What do you think?

**Comment by pitaj** [comment]
It looks good to me but I'll have to test it tonight.

**Pull request merged**
