### PR TITLE
Remove uneccessary text/css definition

### PR DESCRIPTION
**Pull request by RoiEXLab**
This PR adds alt attributes to every img tag in this repo to satisfy the HTML validator, also a minor "violation" regarding a single style element has been fixed.
I'm not exactly sure if the alt description is actually good, feel free to suggest better descriptions

### CODE REVIEW

**Comment by pichalite** [comment]
@RoiEXLab I suggest using user/group slug for alt attribute in case of user/group img tags.

**Comment by pitaj** [comment]
Yeah there are a few problems here. 

1. These should be translations
2. They should probably have the user name / group name instead

**Comment by RoiEXLab** [comment]
@pitaj Agree that those should be translations, I could open an issue on the core repo if you don't want to
Decreasing the scope of this PR then

**Comment by RoiEXLab** [comment]
@pitaj Bumping.

**Comment by pitaj** [comment]
Yeah why don't you open a new PR with the alt attribute changes, and add the necessary translations in a PR to core. If you'd prefer, you could instead add the translations in a new directory in the persona repo instead, and add it to plugin.json as `"languages": "[dirname]"`

**Pull request merged**
