### PR TITLE
Update quickreply.tpl

### PR DESCRIPTION
**Pull request by TheWorms**
Fix translation text

### CODE REVIEW

**Comment by pitaj** [comment]
Yeah it should probably be a new key.

**Comment by TheWorms** [comment]
ok ;)

**Comment by TheWorms** [comment]
I make commit tonight :)

**Comment by TheWorms** [comment]
> Doesn't this change the text to not include the word "quick"?

it's not important in French to include the word "fast".

we can add new key. :)

**Comment by barisusakli** [comment]
https://github.com/NodeBB/nodebb-theme-persona/commit/c43c2ddbdbb80c3b2c4a338536f6cad4c0e1c56f

**Pull request closed without merging**
