### PR TITLE
Fix SSO providers not showing up at all.

### PR DESCRIPTION
**Pull request by BenLubar**

### CODE REVIEW

**Comment by julianlam** [comment]
Ok to merge if works in master, otherwise rebase into develop please :smile:

**Comment by BenLubar** [comment]
@julianlam I tested it on https://github.com/NodeBB/NodeBB/commit/e87f6f900f5094ce451f4d8e1bea20f5aafe4c27 (NodeBB master), and the bug was discovered on an earlier master (after 1.5.2 was released but before the version was bumped in master)

**Comment by barisusakli** [comment]
https://github.com/NodeBB/nodebb-theme-persona/commit/f1f97650bfa8328c97e32fa1a852b160a33f1493

`.length` should work in both the old t.js and the new benchpress, not sure whats up.

**Comment by BenLubar** [comment]
@barisusakli `true.length > 0` is false.

**Comment by barisusakli** [comment]
@BenLubar alternate logins should be an array no?

**Comment by BenLubar** [comment]
@barisusakli no, the array is named `authentication`

**Comment by barisusakli** [comment]
Nvm this seems like a bug in core, sometimes its an array sometimes a boolean

**Comment by barisusakli** [comment]
set to boolean here https://github.com/NodeBB/NodeBB/blob/master/src/controllers/index.js#L136
but to an empty array here https://github.com/NodeBB/NodeBB/blob/master/src/controllers/index.js#L161

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/9d6922432923e25271b6f0f18be3f59e8c1490be

**Pull request merged**
