### PR TITLE
fix mobile menus not working after manual page refresh

### PR DESCRIPTION
**Pull request by sweetppro**
fix for the mobile menus not working after a manual page reload
as noted here:
https://community.nodebb.org/topic/16467/v2-0-custom-persona-theme-mobile-problems/8

### CODE REVIEW

**Comment by julianlam** [comment]
Hi @sweetppro—I've reviewed the context, but this fix will not work. There was a reason why it was put behind the `action:app.load` callback.

Specifically to your debugging, however, `2286.ab7f70f35005dbd282bd.min.js` this looks like CloudFlare Rocket Loader.

Can you turn it off? NodeBB should work fine with it, but sometimes Rocket Loader is too smart for its own good.

**Comment by sweetppro** [comment]
@julianlam Rocket loader is disabled, but brotli and autominify are enabled. I can test options when I can home

**Comment by sweetppro** [comment]
@julianlam I disabled Auto minify for javascript and CSS, I also disabled Brotli. Rocket Loader has been disabled in my site since 2017 (it was causing issues with other apps I run). I also tried changing the caching level to `No query string` and `Ignore query string`.

I even disabled CloudFlare by putting it in development mode.

The only way the menus reliably work on my site is with this PR...

Do you have any other suggestions?

**Comment by julianlam** [comment]
Sorry for the delay -- so even with the auto minify disabled, you're still seeing that kind of file?

Let me put it behind a hooks call... then you can try again.

**Comment by sweetppro** [comment]
@julianlam yup,
the only way to get it working on my site was via https://github.com/NodeBB/nodebb-theme-persona/pull/550

**Comment by julianlam** [comment]
Can you try with v12.0.4 of Persona?

**Comment by julianlam** [comment]
@sweetppro Ah, sorry, I did not see your new PR. Give mine a try first, and see? Listening for widget load seems unrelated, but worth investigating if my fix doesn't work.

**Comment by sweetppro** [comment]
@julianlam yup, your fix that works great!
👍

**Comment by julianlam** [comment]
Excellent!

**Pull request closed without merging**
