### PR TITLE
remove user redirect for guest

### PR DESCRIPTION
**Pull request by pichalite**
fixes NodeBB/NodeBB#4311

### CODE REVIEW

**Comment by barisusakli** [comment]
What fails? looks good to me on t.js 0.3.3

**Comment by pichalite** [comment]
check any category page as a guest on the community.

https://community.nodebb.org/category/1/announcements

**Comment by barisusakli** [comment]
Interesting it doesn't happen on /recent even though it uses topic_list.tpl as well.

**Comment by barisusakli** [comment]
I fixed it by removing the outer if-else-endif

https://github.com/NodeBB/nodebb-theme-persona/commit/9852eaa25385550fe16682777d1956f12269a892

Until @psychobunny fixes it in t.js :trollface:

**Comment by pichalite** [comment]
created a test case on t.js repository for this. if-else-endif seems to be unstable if its nested.

I am also running into issues with this for a change that I am working on the material theme. Breaking the if-else-endif into two if's to work around the issue.

**Comment by barisusakli** [comment]
Yeah nested if-else-endif blocks seems to be the issue. Luckily we can break it down to 

```
if a 
endif a
if !a
endif !a
```
which seems to work.

**Pull request merged**
