### PR TITLE
Block changing items.

### PR DESCRIPTION
**Pull request by youhosi**
Buttons for editing, deleting, changing items blocked for guests and other users on our profile.

### CODE REVIEW

**Comment by barisusakli** [comment]
I am not sure about the isSelf check, admins should be able to change the cover picture of other users

**Comment by youhosi** [comment]
Unfortunately, I did not see that it was possible to check two options, eg isSelf or isAdmin.

**Comment by barisusakli** [comment]
You should be able to use `<!-- IF canEdit-->`

**Comment by youhosi** [comment]
Corrected and everything works (I tested on the local server.)

**Comment by barisusakli** [comment]
Thanks 👍

**Pull request merged**
